### PR TITLE
23 ncbi taxon

### PR DESCRIPTION
**Pull request by bbartley**
Implement #23

### CODE REVIEW

**Comment by PRUBHTEJ** [comment]
Thanks for helping me out, Bryan!
I had a question pertaining to this.
For Systems Ontology, we simply use: - print(SO.promoter)
In this case, what should be that statement, inside print, since NCBITaxon does not work for me?

**Comment by bbartley** [comment]
@PRUBHTEJ firstly, are you working from the source repository for tyto, or are you working with a distribution package installed via pip?  If the latter case, then it isn't working because I haven't deployed the update yet.

It should work as simply as:
```
print(tyto.NCBITaxon.Escherichia_coli)
```

**Comment by PRUBHTEJ** [comment]
Yes, I'm using pip, Bryan. If you could deploy the update, that would be
really helpful.

**Comment by bbartley** [comment]
@PRUBHTEJ these changes are now available in the pip distribution for 1.0b0.  Please update your package

**Comment by PRUBHTEJ** [comment]
Thanks, @bbartley. I'm grateful for your help and guidance.

**Pull request merged**
